### ISSUE TITLE
Running issue for missing data from migrations

### ISSUE THREAD

**Issue by simonv3** [resonatecoop/api#89]
This is an issue for tracking things that look a little odd or off with the current database. Testing against https://dev.resonate.coop/docs

* [x] `user_group.description` and `user_group.bio` columns look like they should have a lot more data in them. But since these tables are currently just copied over from the `user-api` table verbatim and the current production app has the _same_ missing data, I think this is because the original migration _into_ the `user-api` database didn't capture all the descriptions from the `rsntr_user_meta` table.
* [x] Old membership information see #66 
* [x] `user.display_name` is blank for most users, but it should probably feed in the user's user_group if there is a one-to-one link.
* [x] Don't migrate links that are empty strings
* [x] Is there anything in place to actually track user group membership of itself? For example, artists being part of labels? As part of this, it kind of looks like a lot of the migrations into the DB that are labeled as "Label" are actually artists. :thinking:  #101 
* [x] Why is there still a rsntr_usermeta table? Let's delete it! #15

**Comment by simonv3** [comment]
I couldn't find where bios are stored.
